# Task 1 – Data Preview & Validation

This notebook is used to preview and validate the fashion dataset collected using web scraping.

The dataset will be used in future tasks:
- Task 2: Exploratory Data Analysis
- Task 3: Data Visualization
- Task 4: Sentiment Analysis

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/fashion_products.csv")

In [3]:
df.head()

,product_name,category,price,product_url,image_url
0,Abominable Hoodie,Fashion,$69.00,https://www.scrapingcourse.com/ecommerce/produ...,https://www.scrapingcourse.com/ecommerce/wp-co...
1,Adrienne Trek Jacket,Fashion,$57.00,https://www.scrapingcourse.com/ecommerce/produ...,https://www.scrapingcourse.com/ecommerce/wp-co...
2,Aeon Capri,Fashion,$48.00,https://www.scrapingcourse.com/ecommerce/produ...,https://www.scrapingcourse.com/ecommerce/wp-co...
3,Aero Daily Fitness Tee,Fashion,$24.00,https://www.scrapingcourse.com/ecommerce/produ...,https://www.scrapingcourse.com/ecommerce/wp-co...
4,Aether Gym Pant,Fashion,$74.00,https://www.scrapingcourse.com/ecommerce/produ...,https://www.scrapingcourse.com/ecommerce/wp-co...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_name  16 non-null     object
 1   category      16 non-null     object
 2   price         16 non-null     object
 3   product_url   16 non-null     object
 4   image_url     16 non-null     object
dtypes: object(5)
memory usage: 768.0+ bytes

In [5]:
df.describe(include="all")

,product_name,category,price,product_url,image_url
count,16,16,16,16,16
unique,16,1,14,16,16
top,Abominable Hoodie,Fashion,$69.00,https://www.scrapingcourse.com/ecommerce/produ...,https://www.scrapingcourse.com/ecommerce/wp-co...
freq,1,16,2,1,1

## Dataset Validation Summary

- The dataset was successfully scraped from a public e-commerce website.
- All required attributes such as product name, price, and URLs are present.
- The dataset is clean and ready for further analysis and visualization.